jobs:
  - name: paginate req #job name
    dir:  ~infrastructure_dir~/paginator #directory generate file
    template: ~template~/paginate_req.text #template for generate file
    file_name: paginate_req.go #generated file name
    active: true #active/nonactive job
    single_execute: true
    tags:
      #list of tag, that can executed by group of tag
      - init
      - infrastructure
      - paginator

  - name: pagination #job name
    dir: ~infrastructure_dir~/paginator #directory generate file
    template: ~template~/pagination.text #template for generate file
    file_name: pagination.go #generated file name
    active: true #active/nonactive job
    single_execute: true
    tags:
      #list of tag, that can executed by group of tag
      - init
      - infrastructure
      - paginator


  - name: paginator #job name
    dir: ~infrastructure_dir~/paginator #directory generate file
    template: ~template~/paginator.text #template for generate file
    file_name: paginator.go #generated file name
    active: true #active/nonactive job
    single_execute: true
    tags:
      #list of tag, that can executed by group of tag
      - init
      - infrastructure
      - paginator

  - name: DB transaction #job name
    dir: ~infrastructure_dir~/db_transaction #directory generate file
    template: ~template~/db_transaction.text #template for generate file
    file_name: paginator.go #generated file name
    active: true #active/nonactive job
    single_execute: true
    tags:
      #list of tag, that can executed by group of tag
      - init
      - infrastructure
      - transaction

  - name: DB transaction gorm #job name
    dir: ~infrastructure_dir~/db_transaction/gorm_transaction #directory generate file
    template: ~template~/gorm_transaction.text #template for generate file
    file_name: gorm_transaction.go #generated file name
    active: true #active/nonactive job
    single_execute: true
    tags:
      #list of tag, that can executed by group of tag
      - init
      - infrastructure
      - transaction

  - name: ENV Index Conf #job name
    dir: ~infrastructure_dir~/env/conf #directory generate file
    template: ~template~/config_index.text #template for generate file
    file_name: index.go #generated file name
    active: true #active/nonactive job
    single_execute: true
    tags:
      #list of tag, that can executed by group of tag
      - init
      - infrastructure
      - env

  - name: ENV Mysql Conf #job name
    dir: ~infrastructure_dir~/env/conf #directory generate file
    template: ~template~/config_mysql.text #template for generate file
    file_name: mysql.go #generated file name
    active: true #active/nonactive job
    single_execute: true
    tags:
      #list of tag, that can executed by group of tag
      - init
      - infrastructure
      - env

  - name: ENV Pgsql Conf #job name
    dir: ~infrastructure_dir~/env/conf #directory generate file
    template: ~template~/config_pgsql.text #template for generate file
    file_name: pgsql.go #generated file name
    active: true #active/nonactive job
    single_execute: true
    tags:
      #list of tag, that can executed by group of tag
      - init
      - infrastructure
      - env

  - name: ENV Default Conf #job name
    dir: ~infrastructure_dir~/env/conf #directory generate file
    template: ~template~/config_default.text #template for generate file
    file_name: default.go #generated file name
    active: true #active/nonactive job
    single_execute: true
    tags:
      #list of tag, that can executed by group of tag
      - init
      - infrastructure
      - env

  - name: ENV Cors Conf #job name
    dir: ~infrastructure_dir~/env/conf #directory generate file
    template: ~template~/config_cors.text #template for generate file
    file_name: cors.go #generated file name
    active: true #active/nonactive job
    single_execute: true
    tags:
      #list of tag, that can executed by group of tag
      - init
      - infrastructure
      - env
      - cors

  - name: ENV System Conf #job name
    dir: ~infrastructure_dir~/env/conf #directory generate file
    template: ~template~/config_system.text #template for generate file
    file_name: system.go #generated file name
    active: true #active/nonactive job
    single_execute: true
    tags:
      #list of tag, that can executed by group of tag
      - init
      - infrastructure
      - env

  - name: ENV Log Conf #job name
    dir: ~infrastructure_dir~/env/conf #directory generate file
    template: ~template~/config_log.text #template for generate file
    file_name: log.go #generated file name
    active: true #active/nonactive job
    single_execute: true
    tags:
      #list of tag, that can executed by group of tag
      - init
      - infrastructure
      - env

  - name: ENV  #job name
    dir: ~infrastructure_dir~/env #directory generate file
    template: ~template~/env.text #template for generate file
    file_name: env.go #generated file name
    active: true #active/nonactive job
    single_execute: true
    tags:
      #list of tag, that can executed by group of tag
      - init
      - infrastructure
      - env

  - name: Env Conf  #job name
    dir: ~infrastructure_dir~/env #directory generate file
    template: ~template~/conf.text #template for generate file
    file_name: conf.go #generated file name
    active: true #active/nonactive job
    single_execute: true
    tags:
      #list of tag, that can executed by group of tag
      - init
      - infrastructure
      - env

  - name: ENV Viper  #job name
    dir: ~infrastructure_dir~/env #directory generate file
    template: ~template~/viper.text #template for generate file
    file_name: viper.go #generated file name
    active: true #active/nonactive job
    single_execute: true
    tags:
      #list of tag, that can executed by group of tag
      - init
      - infrastructure
      - env

  - name: Datastore  #job name
    dir: ~infrastructure_dir~/datastore #directory generate file
    template: ~template~/gorm_loader.text #template for generate file
    file_name: gorm_loader.go #generated file name
    active: true #active/nonactive job
    single_execute: true
    tags:
      #list of tag, that can executed by group of tag
      - init
      - infrastructure
      - datastore

  - name: Logger lumberjack  #job name
    dir: ~infrastructure_dir~/logger #directory generate file
    template: ~template~/lumberjack.text #template for generate file
    file_name: lumberjack.go #generated file name
    active: true #active/nonactive job
    single_execute: true
    tags:
      #list of tag, that can executed by group of tag
      - init
      - infrastructure
      - datastore

  - name: Utils  #job name
    dir: ~infrastructure_dir~/utils #directory generate file
    template: ~template~/utils.text #template for generate file
    file_name: utils.go #generated file name
    active: true #active/nonactive job
    single_execute: true
    tags:
      #list of tag, that can executed by group of tag
      - init
      - infrastructure
      - utils

  - name: Middleware ECHO Cors  #job name
    dir: ~infrastructure_dir~/middleware/echo_middleware #directory generate file
    template: ~template~/echo_md_cors.text #template for generate file
    file_name: cors_middleware.go #generated file name
    active: true #active/nonactive job
    single_execute: true
    tags:
      #list of tag, that can executed by group of tag
      - init
      - infrastructure
      - utils
      - cors