jobs:
- name: ~module~ request #job name
  dir:  ~app_dir~/domain/request/~module~_request #directory generate file
  template: ~template~/param_request.text #template for generate file
  file_name: param_~module~.go #generated file name
  active: true #active/nonactive job
  tags:
    #list of tag, that can executed by group of tag
    - init
    - request
    - repository
    - param_get
    - param

- name: ~module~ store #job name
  dir:   ~app_dir~/domain/request/~module~_request #directory generate file
  template: ~template~/param_store.text #template for generate file
  file_name: store_~module~.go #generated file name
  active: true #active/nonactive job
  tags:
    #list of tag, that can executed by group of tag
    - init
    - param_store
    - repository
    - param

- name: ~module~ update #job name
  dir:   ~app_dir~/domain/request/~module~_request #directory generate file
  template: ~template~/param_update.text #template for generate file
  file_name: update_~module~.go #generated file name
  active: true #active/nonactive job
  tags:
    #list of tag, that can executed by group of tag
    - init
    - request
    - repository
    - param_update
    - param

