jobs:
  - name: ~module~ repository #job name
    dir:   ~app_dir~/repository/~model_snake~_repository/~model_snake~_gorm #directory generate file
    template: ~template~/repository_gorm.text #template for generate file
    file_name: ~module~_repository.go #generated file name
    active: true #active/nonactive job
    tags:
      #list of tag, that can executed by group of tag
      - init
      - repository

  - name: ~module~ repository interface #job name
    dir:  ~app_dir~/repository/~model_snake~_repository #directory generate file
    template: ~template~/repository_interfaces.text #template for generate file
    file_name: ~module~_repository.go #generated file name
    active: true #active/nonactive job
    tags:
      #list of tag, that can executed by group of tag
      - init
      - repository
      - repository_interface

  - name: ~module~ filter #job name
    dir:  ~app_dir~/repository/~model_snake~_repository/~model_snake~_gorm #directory generate file
    template: ~template~/filter_gorm.text #template for generate file
    file_name: ~module~_filter.go #generated file name
    active: true #active/nonactive job
    tags:
      #list of tag, that can executed by group of tag
      - init
      - repository
      - filter


