jobs:
  - name: ~module~ response #job name
    dir:  ~app_dir~/domain/response/~module~_response #directory generate file
    template: ~template~/paginate_response.text #template for generate file
    file_name: paginate_~module~.go #generated file name
    active: true #active/nonactive job
    tags:
      #list of tag, that can executed by group of tag
      - init
      - response
      - repository