jobs:
- name: main #job name
  dir:  ~app_dir~ #directory generate file
  template: ~template~/main.text #template for generate file
  file_name: main.go #generated file name
  active: true #active/nonactive job
  single_execute: true
  generate_in:  #replace code @GenerateIn [key] in file with this job
  tags:
    #list of tag, that can executed by group of tag
    - init
    - structure
    - main


- name: cmd #job name
  dir:   ~app_dir~/cmd #directory generate file
  template: ~template~/cmd_app.text #template for generate file
  file_name: my_app.go #generated file name
  active: true #active/nonactive job
  single_execute: true
  tags:
    #list of tag, that can executed by group of tag
    - structure
    - init
    - cmd

- name: inject dependency #job name
  dir:   ~app_dir~/cmd #directory generate file
  template: ~template~/dependencies.text #template for generate file
  file_name: my_app.go #generated file name
  active: true #active/nonactive job
  generate_in: dependencies #replace code @GenerateIn [key] in file with this job
  tags:
    #list of tag, that can executed by group of tag
    - structure
    - init
    - dependency